{% set name = "readme_renderer" %}
{% set version = "40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f77b519d96d03d7d7dce44977ba543090a14397c4f60de5b6eb5b8048110aa4

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv '

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - bleach >=2.1.0
    - cmarkgfm >=0.8.0
    - docutils >=0.13.1
    - pygments >=2.5.1
    - python

test:
  requires:
    - pip
  imports:
    - readme_renderer
  source_files:
    - README.rst
  commands:
    - pip check
    - python -m readme_renderer README.rst

about:
  home: https://github.com/pypa/readme_renderer
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://github.com/pypa/readme_renderer
  dev_url: https://github.com/pypa/readme_renderer
  description: readme_renderer is a library for rendering readme descriptions for Warehouse
  documentation: https://pypi.org/project/cmarkgfm/
  summary: readme_renderer is a library for rendering readme descriptions for Warehouse

extra:
  recipe-maintainers:
    - beenje
