{% set name = "readme_renderer" %}
{% set version = "44.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8712034eabbfa6805cacf1402b4eeb2a73028f72d1166d6f5cb7f9c047c5d1e1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - nh3 >=0.2.14
    - docutils >=0.21.2
    - pygments >=2.5.1
  run_constrained:
    # md
    - cmarkgfm >=0.8.0

test:
  source_files:
    - README.rst
    - tests
  imports:
    - readme_renderer
  commands:
    - pip check
    # test_rst_fixtures[test_rst_008.rst]
    # E   Module not found 'types_docutils' -> https://pypi.org/project/types-docutils
    - pytest -v tests --deselect=tests/test_rst.py::test_rst_fixtures[test_rst_008
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pypa/readme_renderer
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://github.com/pypa/readme_renderer
  dev_url: https://github.com/pypa/readme_renderer
  description: readme_renderer is a library for rendering readme descriptions for Warehouse
  summary: readme_renderer is a library for rendering readme descriptions for Warehouse

extra:
  recipe-maintainers:
    - beenje
