{% set name = "readme_renderer" %}
{% set version = "36.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f71aeef9a588fcbed1f4cc001ba611370e94a0cd27c75b1140537618ec78f0a2

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - bleach >=2.1.0
    - cmarkgfm >=0.8.0
    - docutils >=0.13.1
    - pygments >=2.5.1
    - python >=3.7

test:
  imports:
    - readme_renderer
  source_files:
    - README.rst
  commands:
    - python -m readme_renderer README.rst

about:
  home: https://github.com/pypa/readme_renderer
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: readme_renderer is a library for rendering "readme" descriptions for Warehouse

extra:
  recipe-maintainers:
    - beenje
