travis:
  secure:
    BINSTAR_TOKEN: nYIRMv0rMaJUWjkMYejp8ddZjUnZFBOd69a0pZLDCmSSR1Mhf0QF7jHoeMzv6/vT8y0Z9KvANOMfy1cRdbPHqL3XoWvb5W+Q11sYfaWTuy+1XTgX1KNicOE0XnZtsuspuRfpe3fuNd6uL+8mNBj7y2gX3hD9pFl+i7Yld02av5AmMNHRXE/V/tOCIwBUG8JN0BI4o58ArXw1/16WlQQckdDxXDcb1200e4bYRGNQMWqWENWn1ODX2VETxn6GcNawHyz9lNuaHOfTnPaM/rOJlkebXYFksS/IPUzOoE+EpLudIpdFAN3ydQ2cMEmC9AWpPM6pCkJABC4HdePKn7kYHYo6acQOzWkqQw8aAB/BZ55h8L3U2ixWphWhuc/WnJzOEh82+OgVIO/ti7iFYS1fjaFXamHEv+f4riDz51USyYis2qMVkYX64AyPDXn7ZL76ZWvo55wbRXLu/kT6EeYI/WA7OlU5Wv2cVwJMcd+Pg2kju0N7dxFMd/wPgFacBuMypTq1XuixdJBEbs5CIGyZaZRyTb0ZHKIXyeP7FcYenQj5ye06UIm29jtKRYZDs9NAxzPb7IlLjtH4hwLBJFquVFE7aHHdq4x3C+zODN23YB3uIBCD6O68wgvKR2sLxEoVkOVI7Db6Q7qh1xZw/bzeTH3UktNipcErdQ6Egicapps=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
